name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "731496f4cf82a1291b488abe832f469b9ed70b05706ba49b858e384bdce115ed"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
