name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "545124ab8384de407eb6df6c2e462cfbbc42f6254f0fc01cbfb66bea8b71a78a"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
