name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "851a2669133892ac3148ad83c824cfaf862efe8d05579bc44314f22f810abcae"

[versions]
fabric = "0.15.5"
minecraft = "1.20.1"
