name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8737c351911927b0dcf0ba7135e2208f890873dfee19b003455a8c158934994d"

[versions]
fabric = "0.15.4"
minecraft = "1.20.1"
