name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "177fd28a451322545cf6b0d6472f94460180189ac91c55c8239811dd01df0c14"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
