name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa5c8aee405789d4a7a78c39e2bfc0c366e423c9dc0fdb267c24f909c6ee4f84"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
