name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0865bfb43c196d83e2c9607311235852235f102ef5b0ec3f45a72dc7e287f78e"

[versions]
fabric = "0.15.5"
minecraft = "1.20.1"
