name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16dd22d117575a4130c9e8e8d2d7dd6988641f2995c1c9ceb3def58669a91b1a"

[versions]
fabric = "0.15.5"
minecraft = "1.20.1"
