name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "556ee713ac14ced904fdcf4073dfaef5e7a4693883627d380ae1aa57e20c2ba4"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
