name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "483abc19f0e18cf9775fd8a02f71ceadcf84d73c7ed80aaf842bd52fff2c46ea"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
