name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc70cf0980584086e26afecf9413b3af3e91a70d5d805a0a6d64967480274585"

[versions]
fabric = "0.15.4"
minecraft = "1.20.1"
