name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0b867cfcf1b4509818d6567b76c331220fe65a5bd729ac65d1feb29adc925eb"

[versions]
fabric = "0.15.5"
minecraft = "1.20.1"
