name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c0377a99831924bcbe4cefe44a88c18052cc761ed527ed548660ac0eee08a4e"

[versions]
fabric = "0.15.5"
minecraft = "1.20.1"
