name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3156175b16a7f67971d85c30874697f62393c64cca65cc2e067805eef5714fbc"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
