name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7597179c0173136a8068ea6b777d226f08733e0e20a9ce4a11a0059e5eafd6da"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
