name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4689cb87fc2790d5e37e8d96db5aaed1d46846e1041e2e3af74b643ad637c20"

[versions]
fabric = "0.15.4"
minecraft = "1.20.1"
