name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "086b8adf5309dfc1c7f2d16964d35d63df6e81a8070d310f3dddab92c181c8ca"

[versions]
fabric = "0.15.4"
minecraft = "1.20.1"
